services:
  mysql:
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    container_name: r3plica-mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    image: mysql
    ports:
      - '3306:3306'
